name: Full build and publish with versioning
on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
permissions:
  contents: write
jobs:

  build-linux-ubuntu:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 # Fetch full history for branches

      - name: Checking out the correct branches for submodules
        run: |
          git submodule foreach '
          if [ "$name" = "pythonCode/submodules/MEDimage" ]; then
            git fetch origin && git checkout -B dev_lab origin/dev_lab && git pull origin dev_lab
          elif [ "$name" = "pythonCode/submodules/MEDprofiles" ]; then
            git fetch origin && git checkout -B fusion_MEDomicsLab origin/fusion_MEDomicsLab && git pull origin fusion_MEDomicsLab
          else
            echo "No branch specified for $name"
          fi
          '

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.13

      - name: Get tag name
        run: |
          VERSION=${GITHUB_REF/refs\/tags\//}
          NEW_VERSION="${VERSION}"
          node -p "let pkg=require('./package.json'); pkg.version='$NEW_VERSION'; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"

      - name: Print package.json
        run: cat package.json

      - name: Install dependencies
        run: npm install

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build go
        run: |
          cd go_server
          go build main.go 
          cd ..

      - name: Prebuild libmongocrypt
        run: bash ./utilScripts/libmongocrypt_prebuild.sh

      - name: Build for Linux
        run: npm run build:linux

      - name: Get tag name
        id: get-tag
        run: |
          VERSION=${GITHUB_REF/refs\/tags\//}
          echo "VERSION=${VERSION#v}" >> "$GITHUB_OUTPUT"

      - name: Rename Linux
        run: mv ./build/dist/MEDomics-${{ env.VERSION }}-linux.deb ./build/dist/MEDomics-${{ env.VERSION }}-ubuntu.deb
        env:
          VERSION: ${{ steps.get-tag.outputs.VERSION }}

      - name: Archive Linux
        uses: actions/upload-artifact@v4
        with:
          name: linux-built-ubuntu
          path: ./build/dist/MEDomics-${{ env.VERSION }}-ubuntu.deb
          compression-level: 0
          if-no-files-found: error
        env:
          VERSION: ${{ steps.get-tag.outputs.VERSION }}

  # Publish to GitHub
  publish:
    needs: [build-linux-ubuntu]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Linux Ubuntu
        uses: actions/download-artifact@v4
        with:
          name: linux-built-ubuntu

      - name: Get tag name
        id: get-tag
        run: |
          VERSION=${GITHUB_REF/refs\/tags\//}
          echo "VERSION=${VERSION#v}" >> "$GITHUB_OUTPUT"

      - name: Publish to GitHubs
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./latest.yml
            ./MEDomics-${{ env.VERSION }}-ubuntu.deb
          name: MEDomics-${{ env.VERSION }}
          body: |
            MEDomics-${{ env.VERSION }}
            This is a full release of MEDomics. This release includes the MEDomics platform and the Python environment.
            Refer to the [Documentation](https://medomicslab.gitbook.io/medomics-docs/)
            ${{ github.ref }}
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.get-tag.outputs.VERSION }}
